[package]
name = "async_pipeline"
version = "0.1.0"
edition = "2024"

[dependencies]
atomic_refcell = "0.1.13"
futures = "0.3.31"
pin-project-lite = "0.2.16"

[dev-dependencies]
rand = "0.9.2"
tokio = { version = "1.48.0", features = ["full"] }
